---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weave-flux-helm-operator
  annotations:
    flux.weave.works/ignore: "true"
  labels:
    name: weave-flux-helm-operator
    app: weave-flux
    weave-cloud-component: flux
    weave-flux-component: helm-operator
  namespace: weave
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: weave-flux-helm-operator
        app: weave-flux
        weave-cloud-component: flux
        weave-flux-component: helm-operator
    spec:
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400 # when mounted read-only, we won't be able to chmod
      serviceAccountName: weave-flux
      containers:
      - name: weave-flux-helm-operator
        image: 'quay.io/weaveworks/helm-operator:0.1.0-alpha'
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true # this will be the case perforce in K8s >=1.10
        args:
        # replace (at least) the following URL
        - '--git-url=ssh://git@github.com/yuichi10/flux-helm-test'
        - '--git-branch=master'
        - '--git-charts-path=charts'
